---
name: Deploy Collection

on:
    push:
        tags:
            - "*.*.*"

jobs:
    release-galaxy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and Deploy Collection
              uses: artis3n/ansible_galaxy_collection@v2
              with:
                  api_key: "${{ secrets.GALAXY_API_KEY }}"
                  galaxy_version: "${{ github.ref_name }}"

    release-docker:
        needs: release-galaxy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: 🔧 Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: 🔧 Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: 🐋 Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  build-args: VERSION=${{ github.ref_name }}
                  context: docker
                  push: true
                  platforms: linux/amd64,linux/arm64
                  tags: |
                      infisical/ansible-collection:latest
                      infisical/ansible-collection:${{ github.ref_name }}
